global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "dispatch_service"
    static_configs:
      - targets: ["host.docker.internal:8090"]

  - job_name: "system"
    static_configs:
      - targets: ["host.docker.internal:9100"]
